services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    links:
      - db:db
    networks:
      - django_network
  db:
    image: postgres:16.4-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - PGUSER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgresql
    networks:
      - django_network
networks:
  django_network:
    driver: bridge

volumes:
  postgres_data:
