# Generated by Django 4.2.3 on 2024-11-13 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuttingInstructions', '0002_alter_cuttinginstruction_primals_alter_primal_cuts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttinginstruction',
            name='primals',
        ),
        migrations.RemoveField(
            model_name='primal',
            name='cuts',
        ),
        migrations.AddField(
            model_name='cut',
            name='primal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuttingInstructions.primal'),
        ),
        migrations.AddField(
            model_name='primal',
            name='cutting_instructions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuttingInstructions.cuttinginstruction'),
        ),
    ]
